Repository codice/ddf-ui, pull requests merged in 2020-12, with the labels that each got.

#463 Adds multivalued highlighting on the UI, makes highlight structure easier to use
  pom.xml
  ui-backend/catalog-plugin-highlight/pom.xml
  ui-backend/catalog-plugin-highlight/src/main/java/org/codice/ddf/catalog/ui/plugin/highlight/HighlightTransformPlugin.java
  ui-backend/catalog-plugin-highlight/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  ui-backend/catalog-plugin-highlight/src/test/java/org/codice/ddf/catalog/ui/plugin/highlight/HighlightTransformPluginTest.java
  ui-backend/intrigue-ui-app/pom.xml
  ui-backend/intrigue-ui-app/src/main/resources/features.xml
  ui-backend/pom.xml
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/tabs/metacard/highlightUtil.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/tabs/metacard/summary.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/model/LazyQueryResult/LazyQueryResults.tsx
Labels: Hero was successful

#464 Limits limitToDeleted search option to local resources
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/model/Query.js
Labels: Hero was successful

#470 Adds migration capability to cql / filter tree
  .gitattributes
  ui-frontend/package.json
  ui-frontend/packages/admin/package.json
  ui-frontend/packages/admin/yarn.lock
  ui-frontend/packages/catalog-ui-search/package.json
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/filter-builder/filter.structure.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/metacard/metacard.js
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/pages/metacard-nav.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/query-basic/query-basic.view.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/singletons/TypedProperties.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/CQLUtils.js
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/CacheSourceSelector.js
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/cql.js
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/cql.spec.js
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/cql.spec.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/cql.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/filter.js
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/model/LazyQueryResult/LazyQueryResult.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/model/LazyQueryResult/filter.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/model/Query.js
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/model/QueryResult.js
  ui-frontend/packages/catalog-ui-search/yarn.lock
  ui-frontend/packages/cesium-assets/package.json
  ui-frontend/packages/cesium-assets/yarn.lock
  ui-frontend/yarn.lock
Labels: Needs hero

#471 Convert gazetteer autocomplete and add downstream suggestion extension
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js
  ui-frontend/packages/catalog-ui-search/src/main/webapp/extension-points/extension-points.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/auto-complete/auto-complete.js
  ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/auto-complete/auto-complete.spec.js
  ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/auto-complete/auto-complete.stories.js
  ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/auto-complete/gazetteer-autocomplete.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/location/gazetteer.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/location/keyword.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/location/location.tsx
Labels: Current Baseline, Needs review

#466 Update paging to be fuzzy
  ui-backend/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java
  ui-backend/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.xml
  ui-backend/intrigue-ui-app/src/main/resources/etc/org.codice.ddf.catalog.ui.config
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/result-selector/fuzzy-results.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/result-selector/query-feed.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/singletons/TypedProperties.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/properties.js
Labels: Current Baseline, Hero was successful

#473 Search Result Highlighting Update Highlight Style (#6243)
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/theme/theme.tsx
Labels: Current Baseline, Needs hero

#477 Unfuzz available results
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/result-selector/query-feed.tsx
Labels: Current Baseline, Hero was successful

#476 fix default column order for exporting the table
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/table-export/table-export.tsx
Labels: Hero was successful

#481 Fixes a race condition where extension point was referenced too early
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/tabs/metacard/transfer-list.tsx
Labels: Current Baseline, Hero was successful

#478 Make URL attributes into hyperlinks in the summary tab
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/tabs/metacard/highlightUtil.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/tabs/metacard/summary.tsx
Labels: Current Baseline, Hero was successful

#474 Updates CustomFilterInput extension point
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/fields/near.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/extension-points/extension-points.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/filter/filter-input/customInputOrDefault.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/filter/filter-input/filter-input.tsx
Labels: Current Baseline, Hero was successful

#482 Fixes ids for map layers
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/layer-item/layer-item.collection.view.js
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/layers/layers.view.js
  ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/layer-item/layer-item.tsx
Labels: Current Baseline, Hero was successful
