Repository codice/ddf-ui, pull requests merged in 2021-05, with the labels that each got.

#588 [4.2.x] USNG Bbox drawing doesn't update the input values in search
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js
Labels: Hero in progress

#586 USNG Bbox drawing doesn't update the input values in search
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js
Labels: Needs hero

#585 Update query status dropdown and sources popover
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/query-settings/sources-info.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/result-selector/query-feed.tsx
  ui-frontend/packages/catalog-ui-search/tailwind.config.js
Labels: Hero was successful

#584 [4.2.x] DDF 2.26.10 upgrade
  pom.xml
Labels: Hero was successful

#592 [4.2.x] Update table export to use transformFilterTree instead of deleted getEphemeralMixinCql
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/table-export/table-export.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/model/TypedQuery.tsx
Labels: Hero was successful

#594 [4.2.x] Add hook for time settings change to table view
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/results-visual/table.tsx
Labels: Needs review

#595 Add hook for time settings change to table view
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/results-visual/table.tsx
Labels: Hero was successful
