Repository codice/ddf-ui, pull requests merged in 2021-02, with the labels that each got.

#515 [4.1.x] Add source id to audit log
  ui-backend/audit/audit-api/pom.xml
  ui-backend/audit/audit-api/src/main/java/org/codice/ddf/catalog/audit/api/AuditItemBasic.java
  ui-backend/audit/audit-api/src/main/java/org/codice/ddf/catalog/audit/api/AuditItemRequestBasic.java
  ui-backend/audit/audit-api/src/main/java/org/codice/ddf/catalog/audit/api/AuditRequestBasic.java
  ui-backend/audit/audit-api/src/main/java/org/codice/ddf/catalog/audit/api/AuditService.java
  ui-backend/audit/audit-application/src/main/java/org/codice/ddf/catalog/audit/application/AuditHandler.java
  ui-backend/audit/audit-logging/src/main/java/org/codice/ddf/catalog/audit/logging/AuditLogger.java
  ui-backend/audit/audit-logging/src/test/java/org/codice/ddf/catalog/audit/logging/AuditLoggerTest.java
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/visualization/inspector/inspector-lazy.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/utils/audit/audit-endpoint.tsx
Labels: Hero in progress

#516 Add source id to audit log
  ui-backend/audit/audit-api/pom.xml
  ui-backend/audit/audit-api/src/main/java/org/codice/ddf/catalog/audit/api/AuditItemBasic.java
  ui-backend/audit/audit-api/src/main/java/org/codice/ddf/catalog/audit/api/AuditItemRequestBasic.java
  ui-backend/audit/audit-api/src/main/java/org/codice/ddf/catalog/audit/api/AuditRequestBasic.java
  ui-backend/audit/audit-api/src/main/java/org/codice/ddf/catalog/audit/api/AuditService.java
  ui-backend/audit/audit-application/src/main/java/org/codice/ddf/catalog/audit/application/AuditHandler.java
  ui-backend/audit/audit-logging/src/main/java/org/codice/ddf/catalog/audit/logging/AuditLogger.java
  ui-backend/audit/audit-logging/src/test/java/org/codice/ddf/catalog/audit/logging/AuditLoggerTest.java
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/visualization/inspector/inspector-lazy.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/utils/audit/audit-endpoint.tsx
Labels: Needs review

#472 [3.4.x] G-9453 Added CQL Sanitizing method for Search Save and Query Titles
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/query-editor/query-editor.view.js
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/query-title/query-title.view.js
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/model/Query.js
Labels: Old Baseline

#520 [4.1.x] Adds comma delimiter to list values in result item and table results views
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/results-visual/result-item-row.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/results-visual/result-item.tsx
Labels: Hero was successful

#518 [4.1.x] Combine secondary filter in a filter builder class.
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/model/Query.js
Labels: Hero was successful

#521 [4.1.x] Fix start index for export operations and rename visible to current page
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/table-export/table-export.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/model/Query.js
  ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/table-export/container.tsx
Labels: Hero was successful

#523 [4.1.x] Log when a user exports metacards
  ui-backend/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/handlers/CqlTransformHandler.java
  ui-backend/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  ui-backend/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/query/handlers/CqlTransformHandlerTest.java
  ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/utils/export/export.tsx
Labels: Hero was successful

#517 [4.1.x] Adds warning icon when a source status is not successful to heartbeat
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/result-selector/query-feed.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/model/LazyQueryResult/status.tsx
Labels: Hero was successful

#519 Closed heartbeat error warning
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/result-selector/query-feed.tsx
Labels: Hero was successful

#524 [4.1.x] Add possible count to query feed
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/result-selector/query-feed.tsx
Labels: Hero was successful

#525 Add possible count to query feed
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/result-selector/query-feed.tsx
Labels: Hero was successful

#529 [4.1.x] Fix setting Point Radius USNG/MGRS radius
  ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/location/point-radius.js
Labels: Hero was successful

#530 Fix setting Point Radius USNG/MGRS radius
  ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/location/point-radius.js
Labels: Needs review

#528 [4.1.x] Allow date pickers to overflow and fix summary date picker
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/fields/date.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/tabs/metacard/summary.tsx
Labels: Hero was successful

#527 Allow date pickers to overflow and fix summary date picker
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/fields/date.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/tabs/metacard/summary.tsx
Labels: Hero was successful

#502 Add ability to limit buffer to just before or after for around
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/fields/date-around.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/filter-builder/filter.structure.tsx
Labels: Hero was successful

#522 Fix start index for export operations and rename visible to current page
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/table-export/table-export.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/model/Query.js
  ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/table-export/container.tsx
Labels: Hero was successful
