Repository codice/ddf-ui, pull requests merged in 2021-01, with the labels that each got.

#489 Update useEffect dependency to fix stale callback
  ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/location/location.tsx
Labels: Current Baseline, Hero was successful, Needs review

#490 Add 10+ years to the date picker max date
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/fields/date-around.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/fields/date-helpers.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/fields/date-range.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/fields/date-time-picker.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/fields/date.tsx
Labels: Current Baseline

#491 Add context to filter / location for downstream customization
  ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/filter/filter-attribute.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/filter/filter.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/location/location.tsx
Labels: Hero was successful

#462 [3.4.x] G-9207 allow query results to be cleared
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/result-selector/result-selector.view.js
Labels: Old Baseline

#469 [3.4.x] G-8544 Removed 180 degree width constraint on bounding boxes
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.bbox.js
Labels: Old Baseline

#480 [3.4.x] G-9209 fix Search form editor fails to save form with linestring geo
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/CQLUtils.js
Labels: Old Baseline

#483 [3.4.x] G-9195 G-9469 Fix single result export to have user-friendly headers
  ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/results-export/container.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/utils/export/export.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/utils/export/index.tsx
Labels: Old Baseline
