Repository codice/ddf-ui, pull requests merged in 2021-04, with the labels that each got.

#560 Adds handling for doubled wrapped ids in cql parser
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/cql.spec.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/cql.tsx
Labels: Needs hero

#567 [4.2.x] Fix downstream popover overflow
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/query-settings/sources-info.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/extension-points/extension-points.tsx
Labels: Hero was successful

#564 Update export transform to take into account phonetics and spellcheck
  ui-backend/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/handlers/CqlTransformHandler.java
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/table-export/table-export.tsx
Labels: Needs hero

#562 Update source selector / sources button
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/query-settings/source-selector.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/query-settings/sources-info.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/extension-points/extension-points.tsx
Labels: Hero was successful

#570 [4.2.x] 2D Map view zooms in when not active tab
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/map.openlayers.js
Labels: Hero was successful

#571 2D Map view zooms in when not active tab
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/map.openlayers.js
Labels: Hero was successful

#568 [4.2.x] Remove frontend usage of federation, updates query to only use user defaults if flag is passed
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/component.less
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/menu-state/menu-state.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/metacard-menu/metacard-menu.hbs
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/metacard-menu/metacard-menu.less
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/metacard-menu/metacard-menu.view.js
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/metacard/metacard.hbs
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/metacard/metacard.js
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/metacard/metacard.less
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/metacard/metacard.view.js
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/pages/home.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/pages/metacard-nav.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/pages/metacard.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/query-selector/query-selector.less
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/query-selector/query-selector.view.js
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/query-settings/source-selector.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/selection-checkbox/useBackbone.hook.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/selection-interface/selection-interface.model.js
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/singletons/TypedUser.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/model/LazyQueryResult/LazyQueryResults.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/model/LazyQueryResult/sort.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/model/LazyQueryResult/types.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/model/Query.js
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/model/Query.shared-types.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/model/QuerySettings.js
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/model/TypedQuery.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/search-settings/search-settings.tsx
Labels: Hero was successful, Needs review

#573 [4.2.x] Added AnyText and AnyGeo special sort case for Search Attribute
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/singletons/metacard-definitions.js
Labels: Hero was successful

#574 [4.2.x] Update result refresh
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/ResultUtils.js
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/model/QueryResult.js
Labels: Hero was successful

#575 [4.2.x] Fix source property collision
  ui-backend/catalog-plugin-highlight/src/main/java/org/codice/ddf/catalog/ui/plugin/highlight/HighlightTransformPlugin.java
  ui-backend/catalog-plugin-highlight/src/test/java/org/codice/ddf/catalog/ui/plugin/highlight/HighlightTransformPluginTest.java
Labels: Hero was successful

#576 [4.2.x] Add structure for custom metacard update handling for summary view
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/tabs/metacard/summary.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/extension-points/extension-points.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/model/Types.tsx
Labels: Needs review

#578 [4.2.x] Update query status dropdown
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/result-selector/query-feed.tsx
Labels: Hero was successful, Needs review

#579 Update result refresh
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/ResultUtils.js
  ui-frontend/packages/catalog-ui-search/src/main/webapp/js/model/QueryResult.js
Labels: Needs review
