Repository codice/ddf-ui, pull requests merged in 2024-03, with the labels that each got.

#891 Fix timeline visual for multivalued date attributes
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/timeline/timeline.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/timeline/util.tsx
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/visualization/timeline/timeline.tsx
Labels: Hero was successful

#892 Fix timeline for empty data values
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/visualization/timeline/timeline.tsx
Labels: Hero was successful

#899 Fix Dragging Over Antimeridian
  ui-frontend/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.tsx
Labels: question

#897 Delete deleted metacards as current user subject instead of admin
  ui-backend/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/MetacardApplication.java
Labels: Needs hero
